[package]
authors = ["Norbert Pozar <bertapozar@gmail.com>"]
name = "fast_sweeping"
version = "0.0.1"
license = "MIT"

[dependencies]

[dev-dependencies]
gnuplot = "0.0.20"
ndarray = "0.5.1"
quickcheck = "0.2.27"
