[package]
authors = ["Norbert Pozar <bertapozar@gmail.com>"]
license = "MIT"
name = "fast_sweeping"
version = "0.0.1"

[dependencies]

[dev-dependencies]
gnuplot = "0.0.20"
ndarray = "0.5.1"
pbr = "0.1.2"
quickcheck = "0.2.27"
