[package]
authors = ["Norbert Pozar <bertapozar@gmail.com>"]
license = "MIT"
name = "fast_sweeping"
version = "0.0.1"

[dependencies]

[dev-dependencies]
ndarray = "0.6.0"
glium = "0.15.0"
gnuplot = "0.0.21"
pbr = "0.1.2"
quickcheck = "0.2.27"
time = "0.1.35"
